In [1]:
# from utils import *
from fastai2.vision.all import *
from nbdev.showdoc import *
from ipywidgets import widgets
from pandas.api.types import CategoricalDtype

import matplotlib as mpl
# mpl.rcParams['figure.dpi']= 200
mpl.rcParams['savefig.dpi']= 200
mpl.rcParams['font.size']=12

set_seed(42)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
pd.set_option('display.max_columns',999)
np.set_printoptions(linewidth=200)
torch.set_printoptions(linewidth=200)

from fastai2.vision.widgets import *
import time

In [2]:
#from fastai2.learner import load_lerner

In [7]:
!ls models -sh

total 99M
46M chess1.pkl	53M stadard-piece-2.pkl


In [10]:
def piece_class_parse(fn): 
    fn = fn.split('_')[1]
    fn = fn.split('.')[0]
    return fn

In [20]:
learn2 = load_learner('models/chess1.pkl')

In [21]:
learn = load_learner('models/stadard-piece-2.pkl')

In [69]:
img_fns = [ Path('img-tmp/white-pawn-2.jpg'),
            Path('img-tmp/white-bishop-2.jpg'),
            Path('img-tmp/black-knight-2.jpg'),
            Path('img-tmp/white-bishop-3.jpg'),
            Path('img-tmp/black-knight-3.jpg'),]

In [64]:
path = img_fns[0]
print(path)
ret1 = learn.predict(path)
ret2 = learn2.predict(path)
ret1, '\n-----\n', ret2

img-tmp/white-pawn-2.jpg


(('black-bishop',
  tensor(0),
  tensor([8.7558e-01, 1.8214e-02, 6.9944e-03, 5.6010e-05, 4.5798e-03, 1.7799e-03, 7.4306e-03, 1.8005e-03, 6.8108e-02, 5.3980e-04, 1.4241e-02, 6.7362e-04])),
 '\n-----\n',
 ('bishop-chess-piece', tensor(0), tensor([0.9368, 0.0037, 0.0596])))

In [59]:
path = img_fns[1]
print(path)
ret1 = learn.predict(path)
ret2 = learn2.predict(path)
ret1, '\n-----\n', ret2

img-tmp/white-bishop-2.jpg


(('black-bishop',
  tensor(0),
  tensor([7.8089e-01, 2.5202e-02, 2.8375e-03, 4.7862e-05, 4.2133e-03, 1.4603e-03, 6.0035e-03, 8.9760e-04, 2.1610e-02, 8.2166e-04, 1.5548e-01, 5.3737e-04])),
 '\n-----\n',
 ('bishop-chess-piece', tensor(0), tensor([0.7603, 0.0545, 0.1852])))

In [60]:
path = img_fns[2]
print(path)
ret1 = learn.predict(path)
ret2 = learn2.predict(path)
ret1, '\n-----\n', ret2

img-tmp/black-knight-2.jpg


(('black-bishop',
  tensor(0),
  tensor([8.7023e-01, 2.2105e-02, 8.6094e-03, 5.1441e-05, 1.3258e-03, 3.0431e-03, 6.1525e-03, 3.2259e-03, 5.6260e-02, 2.3834e-04, 2.7582e-02, 1.1790e-03])),
 '\n-----\n',
 ('knight-chess-piece', tensor(1), tensor([0.0808, 0.7212, 0.1980])))

In [68]:
path = img_fns[3]
print(path)
ret1 = learn.predict(path)
ret2 = learn2.predict(path)
ret1, '\n-----\n', ret2

img-tmp/white-bishop-3.jpg


(('black-king',
  tensor(1),
  tensor([9.3090e-02, 5.9271e-01, 1.7507e-03, 1.1534e-06, 5.7421e-03, 1.7357e-02, 2.5563e-01, 5.1287e-04, 2.0054e-02, 2.0993e-05, 1.3220e-03, 1.1813e-02])),
 '\n-----\n',
 ('pawn-chess-piece', tensor(2), tensor([0.0360, 0.0161, 0.9480])))

In [70]:
path = img_fns[4]
print(path)
ret1 = learn.predict(path)
ret2 = learn2.predict(path)
ret1, '\n-----\n', ret2

img-tmp/black-knight-3.jpg


(('white-knight',
  tensor(8),
  tensor([2.4380e-01, 8.4150e-03, 2.1388e-02, 5.6534e-05, 2.1004e-03, 1.4356e-02, 8.7938e-05, 5.3382e-04, 6.5479e-01, 1.9675e-07, 2.9393e-03, 5.1530e-02])),
 '\n-----\n',
 ('knight-chess-piece',
  tensor(1),
  tensor([5.4399e-04, 9.9373e-01, 5.7257e-03])))

##### Make a DL to see batch of tfms

In [32]:
path = Path('img-tmp')
pieces = ImageDataLoaders.from_name_func(
                path, 
                get_image_files(path),
                valid_pct=0.1, 
                seed=42,
                label_func=lambda x: x, 
                item_tfms=Resize(128),
#                 item_tfms=RandomResizedCrop(128, min_scale=0.5),
                batch_tfms=aug_transforms(),
                )

In [57]:
type(pieces)

fastai2.data.core.DataLoaders

In [33]:
get_image_files(path)

(#6) [Path('img-tmp/black-knight-1.jpg'),Path('img-tmp/black-knight-2.jpg'),Path('img-tmp/white-bishop-1.jpg'),Path('img-tmp/white-bishop-2.jpg'),Path('img-tmp/white-pawn-1.jpg'),Path('img-tmp/white-pawn-2.jpg')]

In [56]:
pieces.vocab

(#6) ['black-knight-1.jpg','black-knight-2.jpg','white-bishop-1.jpg','white-bishop-2.jpg','white-pawn-1.jpg','white-pawn-2.jpg']