In [1]:
from fastai.text.all import *

### Attach a hook to a pytorch layer
Show it working

In [31]:
lstm = nn.LSTM(2,2)

In [32]:
def my_hook(m,i,o): print('hook fired!')
lstm.register_forward_hook(my_hook)    

In [34]:
x = torch.randn((1,1,2))
lstm(x)

hook fired!


(tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
 (tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
  tensor([[[ 0.2787, -0.5955]]], grad_fn=<StackBackward>)))

### Put that base layer into `WeightDropout`
When doing `__call__` or `forward` on the WeightDropout layer, hook does not fire.

So you do not see "hook fired!" printed out

In [40]:
wd_module = WeightDropout(lstm, .1)

In [41]:
wd_module(x)

(tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
 (tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
  tensor([[[ 0.2787, -0.5955]]], grad_fn=<StackBackward>)))

In [42]:
wd_module.forward(x)

(tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
 (tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
  tensor([[[ 0.2787, -0.5955]]], grad_fn=<StackBackward>)))

### Show how the hook works if you call the inside layer
by calling the lstm layer inside of the WeightDropout layer, we see the hook is still there.

In [43]:
wd_module.module(x)

hook fired!


(tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
 (tensor([[[ 0.1727, -0.1081]]], grad_fn=<StackBackward>),
  tensor([[[ 0.2787, -0.5955]]], grad_fn=<StackBackward>)))